### ISSUE TITLE
Explorer not complete  working with example.

### ISSUE THREAD

**Issue by vad11** [RobinCK/vue-ls#10]
Chrome OK.
Explorer change variables from one vindow to next, BUT if I click in next window, I not see changes in first.

**Comment by RobinCK** [comment]
@vad11 
Everything is working.
https://monosnap.com/file/2GLqjUqYWno3DxjPPZIZQzkoUJ1Zg7

**Comment by vad11** [comment]
Олег, добрый день!

Попробуй поставить окна рядом, чтобы видеть сразу два результата. В хроме
при нажатии меняются стазу два окна, в Експлоре только одно.  Как ты
показал и у меня работает.

2017-07-19 9:37 GMT+03:00 Igor Ognichenko <notifications@github.com>:

**Comment by RobinCK** [comment]
like this?
https://monosnap.com/file/19lGu10Y7UP4O5fzvsQgv11fMwf0KA

**Comment by vad11** [comment]
Yes. This work, but I try for chrome  -as you show.
For explorer not work. May be not supported version

version: 10.0.9200.16384

**Comment by RobinCK** [comment]
[This video](https://monosnap.com/file/19lGu10Y7UP4O5fzvsQgv11fMwf0KA) shows internet explorer 10
