### ISSUE TITLE
Code style issues

### ISSUE THREAD

**Issue by YevheniiHerasymchuk** [RobinCK/vue-ls#11]
1) Inside storage.js class `Storage` has second argument `options`, but during your code I haven't found creating new instance of this class with two parameters.
2) Why do you export private methods: `change` and `eventListeners` of `Storage` class only for test purpose?

**Comment by RobinCK** [comment]
Hi @YevheniiHerasymchuk 

1.  Thanks, I'll fix it.
2. Yes. This is wrong and I will correct it later.

**Comment by RobinCK** [comment]
@YevheniiHerasymchuk thanks for your issue.
Issue fixed in master branch
