### ISSUE TITLE
vuex Initial value

### ISSUE THREAD

**Issue by Hatsuhikari** [RobinCK/vue-ls#129]
This problem occurs when I use it to assign a value to the state in vuex.
 
Could you help me with that, please?

![R{UN`Y6JNSRM(@GH2_TNI)2](https://user-images.githubusercontent.com/31069005/62823549-99cf6200-bbc4-11e9-9cd0-e60d94a483a0.png)

**Comment by pedromoraisf** [comment]
I have the same problem, I want to access Vue.ls from my Vuex plugins but I can't
