### ISSUE TITLE
.on not working

### ISSUE THREAD

**Issue by jacobwise** [RobinCK/vue-ls#15]
Trying to add a listener and not having any success. I'm using Vue 2.4.4 in development mode currently.

https://jsfiddle.net/g5ttw9qn/

`   mounted () {
        this.wishlist = Vue.ls.get('wishlist')
        let updateWishlist = (val, oldVal, uri) => {
            console.log('localStorage change', val);
        }
        Vue.ls.on('wishlist', updateWishlist)
        console.log('mounted')
    }`

**Comment by RobinCK** [comment]
Hello, look at my example https://jsfiddle.net/Robin_ck/6x1akv1L/
it works great.

Also see my comment of the castel work of the events https://github.com/RobinCK/vue-ls#note

**Comment by jacobwise** [comment]
Thanks for the quick answer. I misunderstood how localStorage events run. They don't run in the same tab, I was expecting an event to fire on the same page. Also, I was setting the storage from my update method instead of using a watcher like you are doing in your example. Thanks again!

**Comment by leolux** [comment]
> 
> 
> Hello, look at my example https://jsfiddle.net/Robin_ck/6x1akv1L/
> it works great.
> 
> Also see my comment of the castel work of the events https://github.com/RobinCK/vue-ls#note

` this.$ls.on('counter', function(val) {..}` Is never invoked. The example only works because the increment function increments the counter directly. So the example does not really show that the listener works

**Comment by s00d** [comment]
https://jsfiddle.net/27tk6evx/
on doesn't work if there is no tracking for the variable
