### ISSUE TITLE
window.localStorage

### ISSUE THREAD

**Issue by almaweb** [RobinCK/vue-ls#2]
Hello,

Is there any difference between:  
 window.localStorage.setItem('authUser', JSON.stringify(authUser)) And 
Vue.ls.set('authUser', authUser) ?
Because with th  first one data still in localStorage when i reload page...
with  vue.ls i lose all data after reloading.....

**Comment by RobinCK** [comment]
```javascript
Vue.ls.set('authUser', authUser)
```
alternative

```javascript
window.localStorage.setItem('authUser', JSON.stringify({value: authUser, expire: null})) 
```

[Please see tests](https://github.com/RobinCK/vue-ls/blob/master/test/unit/ava/storage.js#L30)
