### ISSUE TITLE
IE SCRIPT5078 error

### ISSUE THREAD

**Issue by zoli** [RobinCK/vue-ls#24]
While using `vue-ls`, I faced an error in internet explorer:
```
SCRIPT5078: Cannot redefine non-configurable property 'length'
File: vue-ls.js, Line: 7, column: 288
```
The error message points to [this line](https://github.com/RobinCK/vue-ls/blob/master/dist/vue-ls.js#L7).

Also checked the [jsFiddle example](https://jsfiddle.net/Robin_ck/6x1akv1L/) in the readme, this error is occuring there to.

**Comment by RobinCK** [comment]
Hi @zoli thanks for your report 
ie fixed in 3.0.3 relise 
and jsFiddle example fixed
