### ISSUE TITLE
Error in 'yarn run production'

### ISSUE THREAD

**Issue by wittonzhao** [RobinCK/vue-ls#3]
Hi, I use `laravel 5.4` and `vue 2.2` for my project, and I choose *vue-ls* for local storage operations. When I use `yarn run production` for package release, I get this error:
```
 ERROR  Failed to compile with 1 errors                                                                                                            6:01:49 PM

 error  

/js/app.js from UglifyJs
Unexpected token: name (ls$1) [./~/vue-ls/dist/vue-ls.esm.js:1,0][/js/app.js:37496,4]

```

Thanks for any help.

**Comment by RobinCK** [comment]
Hello @wittonzhao.
It takes time to test.
In the meantime, you can use:
`Import Ls from 'vue-ls/dist/vue-ls';`

What version of webpack do you use?

**Comment by wittonzhao** [comment]
@RobinCK Thank you. I use `laravel-mix@0.10.0` with `webpack@2.3.3`

**Comment by JGrancha** [comment]
The same error:
Webpack version: 2.4.1
Error:
`ERROR in static/js/vendor.e041221e648979493714.js from UglifyJs                                                                                                         
Unexpected token: name (ls$1) [./~/vue-ls/dist/vue-ls.esm.js:1,0][static/js/vendor.e041221e648979493714.js:30980,4]`
With `Import Ls from 'vue-ls/dist/vue-ls';` not resolve the problem.

**Comment by RobinCK** [comment]
hello 
please update to v2.2.13

**Comment by JGrancha** [comment]
Works! Thanks!
