### ISSUE TITLE
local storage listener on event in Edge and IE

### ISSUE THREAD

**Issue by freeman-g** [RobinCK/vue-ls#4]
Thanks for your plugin!

I was doing some cross browser testing and the following code works in Chrome but not in Edge or IE.

Do you know if this should be supported in Edge and IE?  The getters and setters seem to be working fine in Edge and IE, just not the listener for changes:

```
        this.$ls.on('myKey', storedData => {
          //not fired in Edge/IE
          var myObj = JSON.parse(storedData)
          console.log('heard local storage event from )
        })
```

Thanks!

**Comment by RobinCK** [comment]
Hello.

Please [read](https://github.com/RobinCK/vue-ls#note) and test [example](https://jsfiddle.net/Robin_ck/6x1akv1L/) open two tabs and click increment/decrement.
The value will be updated in both tabs

**Comment by freeman-g** [comment]
@RobinCK thank you - I was JSON.stringify storing a relatively large object with some special characters in local storage and then then JSON.parsing it in another tab.  I think my problem was one of the following:

- IE/Edge didn't like some special characters in the JSON string which cause the event listener not to work
- The string was too big for the IE/Edge event listener (it was 73kb).

I'm not sure which one it was, but I solved it by sending a subset of my object back and forth.  Thanks again.
