### ISSUE TITLE
IE 11 Cannot redefine non-configurable property length

### ISSUE THREAD

**Issue by cdekok** [RobinCK/vue-ls#40]
The library throws this error on IE 11 `IE 11 Cannot redefine non-configurable property length`

**Comment by RobinCK** [comment]
[this example](https://jsfiddle.net/Robin_ck/6x1akv1L/) works well

**Comment by cdekok** [comment]
Strange it was probably something in my build process that caused it, it only happened when importing this package.
Anyway I solved it by just using native LocalStorage and then it worked ok.
