### ISSUE TITLE
Support SSR ?

### ISSUE THREAD

**Issue by be-next-hotdog** [RobinCK/vue-ls#41]
Yopp guys,
just a quick question, does this lib support SSR mode ?
Thx a lot,

**Comment by RobinCK** [comment]
Sorry, I did not work yet with ssr. because I can not tell you how to set it up
Maybe this message will help
https://github.com/RobinCK/vue-gallery/issues/3#issuecomment-335893257

**Comment by be-next-hotdog** [comment]
In contrast, I need to develop my app under SSR mode so the support SSR should be a necessary feature for me.

But thx all the same
