### ISSUE TITLE
Minified file of the library 

### ISSUE THREAD

**Issue by extend1994** [RobinCK/vue-ls#5]
Hi! I am a member of CDNJS and the one in charge of adding your library to our CDN.
I noticed that the file `vue-ls.esm.js` in some old versions is not minified. So I try to minify it by myself using the tool https://github.com/PeterDaveHello/web-minify-helper but failed. However, on CDNJS we want a minified file running on a browser. Could you please provide a minified file or give some other suggestions about it such as "we don't need the file"? Thank you!

P.S. Reference: the error message I got was `SyntaxError: Unexpected token: name (ls$1)`

**Comment by RobinCK** [comment]
Thanks for your message.
This file removed from package.
dist/vue-ls.js - original file 
dist/vue-ls.min.js - minified file

**Comment by extend1994** [comment]
@RobinCK Thanks for reply. So do I just need to add `dist/vue-ls.js` and `dist/vue-ls.min.js`, and don't need `dist/vue-ls.esm.js` in v2.2.0~v2.2.12?

**Comment by RobinCK** [comment]
yes
