### ISSUE TITLE
local storage variable disappear in dev tool

### ISSUE THREAD

**Issue by idris11** [RobinCK/vue-ls#50]
i have write code to assign a varible into local storage
`this.$ls.set('token','13526fgsfyfsayt535627')`
but, token disappear in dev tool. 
In the other condition, i can console.log(this.$ls.get('token'))

**Comment by RobinCK** [comment]
it's work fine
https://monosnap.com/file/zzWIRuIFpKrPgQXhpDC3sWIcgKbalk
