### ISSUE TITLE
Listen a storage from multiple Vue instances in a same page

### ISSUE THREAD

**Issue by Stolka** [RobinCK/vue-ls#70]
Hello RobinCK!

Thanks for making a great plugin!

However I stumbled upon an issue, I'm trying to make 2 instances to listen a storage in a same page.

Example: https://fiddle.jshell.net/Stolka/hbayz0t8/show/

If I changed the data from the first instance, the second counter won't be updated until I reload the page and vice versa.

Is there a way to make both of them to watch the storage changes and update each counter at same time?

Thanks!

**Comment by RobinCK** [comment]
Hello @Stolka, thanks.

Please see the [documentation](https://vuejs.org/v2/guide/state-management.html#Simple-State-Management-from-Scratch)

My example https://jsfiddle.net/Robin_ck/hbayz0t8/12/
