### ISSUE TITLE
unhadled json parsing exception

### ISSUE THREAD

**Issue by gaborcorp** [RobinCK/vue-ls#8]
Hi there,

noticed that when the values are parsed from the local storage (JSON.parse) the exceptions are not handled in case of an invalid or empty value it results in 
Uncaught SyntaxError: Unexpected token  in JSON 

modified your example to include the case here
https://jsfiddle.net/w4eqb1kj/

with vue 2 it seems to be handled later on by vue itself but I guess that also might depend on the lifecycle.

**Comment by RobinCK** [comment]
HI @gaborcorp 
I do not see the difference between your example and mine

**Comment by gaborcorp** [comment]
my bad:
https://jsfiddle.net/w4eqb1kj/1/
line 6

**Comment by RobinCK** [comment]
@gaborcorp thank you. Soon I will fix it.
Thank you. Soon I will fix it.

**Comment by RobinCK** [comment]
fix in v2.2.17
