### ISSUE TITLE
Add Changelog

### ISSUE THREAD

**Issue by chagar** [RobinCK/vue-ls#82]
How do I find out what was changed between releases, most importantly breaking changes? Right now, it's a total fog of war.

Risky to upgrade a package without any idea of what may break or what is involved in major upgrades. No reason to upgrade if there are no significant changes between releases.

Please document what was changed in releases, either in the Github Releases section or in CHANGELOG.md.

**Comment by RobinCK** [comment]
Thank you, I will take into your comment
