### ISSUE TITLE
How to use local and session at the same time

### ISSUE THREAD

**Issue by tigerwei209** [RobinCK/vue-ls#83]
How to use local and session at the same time

**Comment by RobinCK** [comment]
```javascript
const localOptions = {
  namespace: 'vuejs__', // key prefix
  name: 'ls', // name variable Vue.[ls] or this.[$ls],
  storage: 'local', // storage name session, local, memory
};

const sessionOptions = {
  namespace: 'vuejs__', // key prefix
  name: 'session', // name variable Vue.[ls] or this.[$ls],
  storage: 'session', // storage name session, local, memory
};


Vue.use(Storage, sessionOptions);
Vue.use(Storage, localOptions);
```

Think so

**Comment by tigerwei209** [comment]
localStorage use Vue.ls.set('key','value')
sessionStorage use Vue.session.set('key,'value')
but sessionStorage is not work

**Comment by tigerwei209** [comment]
thanks,i have resolved.
`import VueStorage from 'vue-ls'

const VueSessionStorage = {
    /**
     * Install plugin
     *
     * @param {Object} Vue
     * @param {Object} options
     * @returns {WebStorage}
     */
    install(Vue, options = {}) {
        const _options = Object.assign({}, options, {
            storage: options.storage || 'session',
            name: options.name || 'ss',
          });
        VueStorage.install(Vue, _options);
    },
};
  
export default VueSessionStorage;`

`import VueStorage from 'vue-ls'
import VueSessionStorage from './Vuels'

Vue.use(VueStorage, {namespace: 'vuexx__'})
Vue.use(VueSessionStorage, {namespace: 'vuexx__'})`

**Comment by RobinCK** [comment]
const localOptions = {
  namespace: 'vuejs__',
  name: 'ls',
  storage: 'local', 
};

const sessionOptions = {
  namespace: 'vuejs__', 
  name: 'session',
  storage: 'session', 
};


Vue.use(Storage, sessionOptions);
Vue.use(Object.assign({}, Storage), localOptions);
