### ISSUE TITLE
Can't read Vue.$ls 

### ISSUE THREAD

**Issue by Zhuzhenghao** [RobinCK/vue-ls#84]
Sry for my poor English
When I use the plugin in my ts-based project, I can't get the property Vue.$ls .
But I can read Vue.prototype.$ls.
So,I find the property enumerable of the Vue.prototype.$ls is false.
May i ask the propose you cover the property?

**Comment by RobinCK** [comment]
please see https://github.com/RobinCK/vue-ls#global

**Comment by Zhuzhenghao** [comment]
> please see https://github.com/RobinCK/vue-ls#global

thx very much.But can i know why you did not expose the Vue.$ls?
